# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "gyp-merge-0.2.1" = {
      name = "gyp-merge";
      packageName = "gyp-merge";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gyp-merge/-/gyp-merge-0.2.1.tgz";
        sha1 = "d03d12d51282f7b99bca80e3059acaacea439983";
      };
    };
    "gyp-expansions-0.0.2" = {
      name = "gyp-expansions";
      packageName = "gyp-expansions";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gyp-expansions/-/gyp-expansions-0.0.2.tgz";
        sha1 = "e66421a66a461a0d2cf384f8700f17eb14783672";
      };
    };
    "gyp-conditions-0.0.4" = {
      name = "gyp-conditions";
      packageName = "gyp-conditions";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gyp-conditions/-/gyp-conditions-0.0.4.tgz";
        sha1 = "81fbf6635aa081c1f0aec0b804b2779deb0639de";
      };
    };
    "gyp-load-0.5.0" = {
      name = "gyp-load";
      packageName = "gyp-load";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gyp-load/-/gyp-load-0.5.0.tgz";
        sha1 = "12096713a46b0a73610fccd09b528b7e526ee520";
      };
    };
    "ometajs-3.2.4" = {
      name = "ometajs";
      packageName = "ometajs";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ometajs/-/ometajs-3.2.4.tgz";
        sha1 = "807cdf4c0e8df1727f224ca6db1faac43e8bdab1";
      };
    };
    "coa-0.3.9" = {
      name = "coa";
      packageName = "coa";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/coa/-/coa-0.3.9.tgz";
        sha1 = "7e3d20d30af70b80862e95d4d49b715183be9604";
      };
    };
    "q-0.8.12" = {
      name = "q";
      packageName = "q";
      version = "0.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-0.8.12.tgz";
        sha1 = "9162a91e11819c4bcda7da15cf5fefaad0778823";
      };
    };
    "uglify-js-1.3.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-1.3.5.tgz";
        sha1 = "4b5bfff9186effbaa888e4c9e94bd9fc4c94929d";
      };
    };
    "jsonic-ometajs-0.0.0" = {
      name = "jsonic-ometajs";
      packageName = "jsonic-ometajs";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonic-ometajs/-/jsonic-ometajs-0.0.0.tgz";
        sha1 = "54acb69ed170cc2dc87cb62c47a1961c51d14486";
      };
    };
    "json-ometajs-0.0.1" = {
      name = "json-ometajs";
      packageName = "json-ometajs";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-ometajs/-/json-ometajs-0.0.1.tgz";
        sha1 = "35abd65b91f6c3d187d27c92f4b21b9411359996";
      };
    };
    "fstream-1.0.11" = {
      name = "fstream";
      packageName = "fstream";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream/-/fstream-1.0.11.tgz";
        sha1 = "5c1fb1f117477114f0632a0eb4b71b3cb0fd3171";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "npmlog-4.1.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
        sha512 = "2967mavp7zw0aawf5fadqf4pmn7vy5gya1yx2s9wwppvivhd9q4mpdnszfqvd7p6yks649bwbpj8iviw86g0hpp4f93d5ca7dmjmrfs";
      };
    };
    "osenv-0.1.5" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "3ddw0y41pxv08ls5xhmq1bi81hppjbr45k78cjfx99vznh5znrj5g1b1wab9caj1mqlsvmfms0zm9cfb47ygm0d8wv5fccx8049q9fh";
      };
    };
    "request-2.83.0" = {
      name = "request";
      packageName = "request";
      version = "2.83.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.83.0.tgz";
        sha512 = "0by1djkn836sqd9pk2c777wcjvp34qbk1plx7s4lmykljrblpjc64dvn6ni2vyxsbyk33wnl6avym8vgw0ggr4226xakck8mw7y07cm";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "tar-2.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-2.2.1.tgz";
        sha1 = "8e4d2a256c0e2185c6b18ad694aec968b83cb1d1";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha512 = "358cfi3qak701qp5pwkq47n87ca4m8k4lvjl0pdybvmp92nwwd7azzhahy9gy3kg8lqrqdry9l6pl2csflzr0nvwnc3p6asjyi6khn5";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "248cnpbbf0p32h53rd3g8wzpgrkaj4p078ra1g6l16f82i6bzkvmhwqan5rk88apbll9ly1476kngd7f7z27i3b3zxpbb3064f8yaw8";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "38s4f3id97wsb0rg9nm9zvxyq0nvwrmrpa5dzvrkp36mf5ibs98b4z6lvsbrwzzs0sbcank6c7gpp06vcwp9acfhp41rzlhi3ybsxwy";
      };
    };
    "are-we-there-yet-1.1.4" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.4.tgz";
        sha1 = "bb5dca382bb94f05e15194373d16fd3ba1ca110d";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "gauge-2.7.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "2c03405c7538c39d7eb37b317022e325fb018bf7";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "readable-stream-2.3.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.5.tgz";
        sha512 = "09n3j4jsfl2lq3gj65qwn5b3lvzb624lrb8m14h81ls9cw59vvm8436gm5zwaqxf6y1zrfwbrsmizsq48jw1s3qj9zhpjp438735bdl";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "0rw8xpqqkhs91722slvzf8icxfaimqp4w8zb3840jxr7r8n8035byl6dhdi5bm0yr6x7sdws0gf3m025fg6hqgaklwlbl4d7bah5l9j";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha512 = "22vw5mmwlyblqc2zyqwl39wyhyahhpiyknim8iz5fk6xi002x777gkswiq8fh297djs5ii4pgrys57wq33hr5zf3xfd0d7kjxkzl0g0";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "aproba-1.2.0" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
        sha512 = "13mgnbmdhdq0qncijvpip1l39q1a8labcvj3hc3n1yl2zch106mdkn7p7bd5knvmfkkn1js9nd47nzyjk1himbm8ry8i8gd6mk7mlk3";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "wide-align-1.1.2" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.2.tgz";
        sha512 = "39m5b8qc31vxhh0bz14vh9a1kf9znarvlpkf0v6vv1f2dxi61gihav2djq2mn7ns1z3yq6l8pyydj52fyzbm2q04rssrcrv4jbwnc4a";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha512 = "1nl2hjr2mnhj5jlaz8mh54z7acwz5j5idkch04qgjk78756gw5d0fjk4a2immil5ij9ijdssb9ndpryvnh2xpcbgcjv8lxybn330als";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.18" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.18.tgz";
        sha512 = "22krj1kw7n9z10zdyx7smcaim4bzwqsqzhspwha06q58gcrxfp93hw2cd0vk5crhq5p2dwzqlpacg32lrmp5sjzb798zdzy35mdmkwm";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.4" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.4.tgz";
        sha512 = "0ncm6j3cjq1f26mzjf04k9bkw1b08w53s4qa3a11c1bdj4pgnqv1422c1xs5jyy6y1psppjx52fhagq5zkjkgrcpdkxcdiry96r77jd";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "hoek-4.2.1" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.1.tgz";
        sha512 = "1y8kprb3qldxqj31zai5n8dvhydsl9nn5w4rskhnbzzhldn6pm6n5lcyam3sfkb61a62d5m58k8im7z6ngwbd9cw9zp4zm4y7ckrf20";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "sntp-2.1.0" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz";
        sha512 = "0k2smmr24w5hb1cpql6vcgh58vzp4pmh9anf0bgz3arlsgq1mapnlq9fjqr6xs10aq1cmxaw987fwknqi62frax0fvs9bj3q3kmpg8l";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha512 = "19h20yqpvca08dns1rs4f057f10w63v0snxfml4h5khsk266x3x1im0w72bza4k2xn0kfz6jlv001dhcvxsjr09bmbqnysils9m7437";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.33.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.33.0.tgz";
        sha512 = "36xnw59ik9fqym00cmwb5nyzg0l03k70cp413f7639j93wgmzk1mh0xjc7i6zz3r6k9xnwh0g5cm5a1f3y8c6plgy4qld7fm887ywh4";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "block-stream-0.0.9" = {
      name = "block-stream";
      packageName = "block-stream";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream/-/block-stream-0.0.9.tgz";
        sha1 = "13ebfe778a03205cfe03751481ebb4b3300c126a";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "adnn-2.0.10" = {
      name = "adnn";
      packageName = "adnn";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/adnn/-/adnn-2.0.10.tgz";
        sha1 = "4e3bc9b077562f53ce00c16d0e80dd9649eb842b";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ast-types-0.9.14" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.9.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.9.14.tgz";
        sha512 = "0kp7c3669iz0kz5hglc4r8r6nxql77hdqf03fihxig9hkxs7ppmrp08hq81m5fqbkggp312l9w03b0sz07h69i1fw1blb95zppz3fqi";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "escodegen-1.9.1" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.9.1.tgz";
        sha512 = "3nl4jbvigqc5ax1f35b601vlca4fa4ghr27wfglgrmv7h5pssnkh7px0vjh8wzrkjvx8bw7c71b0axc307akkjd1vkl2nj0acxy657a";
      };
    };
    "esmangle-1.0.1" = {
      name = "esmangle";
      packageName = "esmangle";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmangle/-/esmangle-1.0.1.tgz";
        sha1 = "d9bb37b8f8eafbf4e6d4ed6b7aa2956abbd3c4c2";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "estemplate-0.5.1" = {
      name = "estemplate";
      packageName = "estemplate";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estemplate/-/estemplate-0.5.1.tgz";
        sha1 = "1714a9d46190738ac958bcafd49e029cda56a39e";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "lru-cache-4.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.1.tgz";
        sha512 = "1xz91sizgyzh8plz5jx1labzpygapm6xy3qpxriaj00yvnhy4lnmhqcb20qln4lh80c5g3yzp4j5i6g63njq1r5sl9c0zlkh9xjk2xb";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "present-1.0.0" = {
      name = "present";
      packageName = "present";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/present/-/present-1.0.0.tgz";
        sha1 = "6d2f865be7a96885118f4660e83e2161fb71cf2b";
      };
    };
    "priorityqueuejs-1.0.0" = {
      name = "priorityqueuejs";
      packageName = "priorityqueuejs";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/priorityqueuejs/-/priorityqueuejs-1.0.0.tgz";
        sha1 = "2ee4f23c2560913e08c07ce5ccdd6de3df2c5af8";
      };
    };
    "seedrandom-2.4.3" = {
      name = "seedrandom";
      packageName = "seedrandom";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/seedrandom/-/seedrandom-2.4.3.tgz";
        sha1 = "2438504dad33917314bff18ac4d794f16d6aaecc";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "stack-trace-0.0.9" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz";
        sha1 = "a8f6eaeca90674c333e7c43953f275b451510695";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "esutils-1.0.0" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.0.0.tgz";
        sha1 = "8151d358e20c8acc7fb745e7472c0025fe496570";
      };
    };
    "esshorten-1.1.1" = {
      name = "esshorten";
      packageName = "esshorten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esshorten/-/esshorten-1.1.1.tgz";
        sha1 = "174f96b7cc267e46872d814e7db7c290bdff61a9";
      };
    };
    "estraverse-1.5.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.5.1.tgz";
        sha1 = "867a3e8e58a9f84618afb6c2ddbcd916b7cbaf71";
      };
    };
    "escope-1.0.3" = {
      name = "escope";
      packageName = "escope";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-1.0.3.tgz";
        sha1 = "759dce8496c4248fec2d0caaf4108bcf3f1a7f5d";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "escodegen-1.3.3" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.3.3.tgz";
        sha1 = "f024016f5a88e046fd12005055e939802e6c5f23";
      };
    };
    "optionator-0.3.0" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.3.0.tgz";
        sha1 = "9715a8b5f5e7586cff06c8249e039cd7364d3f54";
      };
    };
    "esprima-1.1.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.1.1.tgz";
        sha1 = "5b6f1547f4d102e670e140c509be6771d6aeb549";
      };
    };
    "estraverse-4.1.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.1.1.tgz";
        sha1 = "f6caca728933a850ef90661d0e17982ba47111a2";
      };
    };
    "estraverse-2.0.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-2.0.0.tgz";
        sha1 = "5ae46963243600206674ccb24a09e16674fcdca1";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "levn-0.2.5" = {
      name = "levn";
      packageName = "levn";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.2.5.tgz";
        sha1 = "ba8d339d0ca4a610e3a3f145b9caf48807155054";
      };
    };
    "fast-levenshtein-1.0.7" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.0.7.tgz";
        sha1 = "0178dcdee023b92905193af0959e8a7639cfdcb9";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "nan-2.9.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.9.2.tgz";
        sha512 = "1iwlv98jbkr46c7hy28crk2m89jiskrp4qfa5ysyacyq8dkbk4hii3cc61irf39b7n6wd9cjlaasmakv9dsknqhb3876zrvrbjvmmcn";
      };
    };
  };
in
{
  gyp = nodeEnv.buildNodePackage {
    name = "gyp";
    packageName = "gyp";
    version = "0.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/gyp/-/gyp-0.5.0.tgz";
      sha1 = "4865a4564e5f4b7beff38cb52b8a8a36337456f4";
    };
    dependencies = [
      sources."gyp-merge-0.2.1"
      (sources."gyp-expansions-0.0.2" // {
        dependencies = [
          (sources."ometajs-3.2.4" // {
            dependencies = [
              sources."coa-0.3.9"
              sources."q-0.8.12"
              sources."uglify-js-1.3.5"
            ];
          })
        ];
      })
      (sources."gyp-conditions-0.0.4" // {
        dependencies = [
          (sources."ometajs-3.2.4" // {
            dependencies = [
              sources."coa-0.3.9"
              sources."q-0.8.12"
              sources."uglify-js-1.3.5"
            ];
          })
        ];
      })
      (sources."gyp-load-0.5.0" // {
        dependencies = [
          (sources."jsonic-ometajs-0.0.0" // {
            dependencies = [
              sources."json-ometajs-0.0.1"
              (sources."ometajs-3.2.4" // {
                dependencies = [
                  sources."coa-0.3.9"
                  sources."q-0.8.12"
                  sources."uglify-js-1.3.5"
                ];
              })
            ];
          })
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A gyp file reader / processor";
      license = "BSD";
    };
    production = true;
  };
  node-gyp = nodeEnv.buildNodePackage {
    name = "node-gyp";
    packageName = "node-gyp";
    version = "3.6.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/node-gyp/-/node-gyp-3.6.2.tgz";
      sha1 = "9bfbe54562286284838e750eac05295853fa1c60";
    };
    dependencies = [
      (sources."fstream-1.0.11" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      (sources."glob-7.1.2" // {
        dependencies = [
          sources."fs.realpath-1.0.0"
          (sources."inflight-1.0.6" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."inherits-2.0.3"
          (sources."once-1.4.0" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."path-is-absolute-1.0.1"
        ];
      })
      sources."graceful-fs-4.1.11"
      (sources."minimatch-3.0.4" // {
        dependencies = [
          (sources."brace-expansion-1.1.11" // {
            dependencies = [
              sources."balanced-match-1.0.0"
              sources."concat-map-0.0.1"
            ];
          })
        ];
      })
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      (sources."nopt-3.0.6" // {
        dependencies = [
          sources."abbrev-1.1.1"
        ];
      })
      (sources."npmlog-4.1.2" // {
        dependencies = [
          (sources."are-we-there-yet-1.1.4" // {
            dependencies = [
              sources."delegates-1.0.0"
              (sources."readable-stream-2.3.5" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."inherits-2.0.3"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-2.0.0"
                  sources."safe-buffer-5.1.1"
                  sources."string_decoder-1.0.3"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          sources."console-control-strings-1.1.0"
          (sources."gauge-2.7.4" // {
            dependencies = [
              sources."aproba-1.2.0"
              sources."has-unicode-2.0.1"
              sources."object-assign-4.1.1"
              sources."signal-exit-3.0.2"
              (sources."string-width-1.0.2" // {
                dependencies = [
                  sources."code-point-at-1.1.0"
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.1"
                    ];
                  })
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              sources."wide-align-1.1.2"
            ];
          })
          sources."set-blocking-2.0.0"
        ];
      })
      (sources."osenv-0.1.5" // {
        dependencies = [
          sources."os-homedir-1.0.2"
          sources."os-tmpdir-1.0.2"
        ];
      })
      (sources."request-2.83.0" // {
        dependencies = [
          sources."aws-sign2-0.7.0"
          sources."aws4-1.6.0"
          sources."caseless-0.12.0"
          (sources."combined-stream-1.0.6" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.1"
          sources."forever-agent-0.6.1"
          (sources."form-data-2.3.2" // {
            dependencies = [
              sources."asynckit-0.4.0"
            ];
          })
          (sources."har-validator-5.0.3" // {
            dependencies = [
              (sources."ajv-5.5.2" // {
                dependencies = [
                  sources."co-4.6.0"
                  sources."fast-deep-equal-1.1.0"
                  sources."fast-json-stable-stringify-2.0.0"
                  sources."json-schema-traverse-0.3.1"
                ];
              })
              sources."har-schema-2.0.0"
            ];
          })
          (sources."hawk-6.0.2" // {
            dependencies = [
              sources."hoek-4.2.1"
              sources."boom-4.3.1"
              (sources."cryptiles-3.1.2" // {
                dependencies = [
                  sources."boom-5.2.0"
                ];
              })
              sources."sntp-2.1.0"
            ];
          })
          (sources."http-signature-1.2.0" // {
            dependencies = [
              sources."assert-plus-1.0.0"
              (sources."jsprim-1.4.1" // {
                dependencies = [
                  sources."extsprintf-1.3.0"
                  sources."json-schema-0.2.3"
                  (sources."verror-1.10.0" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                    ];
                  })
                ];
              })
              (sources."sshpk-1.13.1" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."dashdash-1.14.1"
                  sources."getpass-0.1.7"
                  sources."jsbn-0.1.1"
                  sources."tweetnacl-0.14.5"
                  sources."ecc-jsbn-0.1.1"
                  sources."bcrypt-pbkdf-1.0.1"
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
          sources."oauth-sign-0.8.2"
          sources."performance-now-2.1.0"
          sources."qs-6.5.1"
          sources."safe-buffer-5.1.1"
          sources."stringstream-0.0.5"
          (sources."tough-cookie-2.3.4" // {
            dependencies = [
              sources."punycode-1.4.1"
            ];
          })
          sources."tunnel-agent-0.6.0"
          sources."uuid-3.2.1"
        ];
      })
      sources."rimraf-2.6.2"
      sources."semver-5.3.0"
      (sources."tar-2.2.1" // {
        dependencies = [
          sources."block-stream-0.0.9"
          sources."inherits-2.0.3"
        ];
      })
      (sources."which-1.3.0" // {
        dependencies = [
          sources."isexe-2.0.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Node.js native addon build tool";
      homepage = "https://github.com/nodejs/node-gyp#readme";
      license = "MIT";
    };
    production = true;
  };
  node-gyp-build = nodeEnv.buildNodePackage {
    name = "node-gyp-build";
    packageName = "node-gyp-build";
    version = "3.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-3.3.0.tgz";
      sha512 = "0vkilw1ghsjca0lrj9gsdgsi8wj4bvpfr25q1qzx1kp5hhvjdhapmvpmrd2hikwq9dxydw6sdvv0730wwvmsg36xqf0hgp9777l3ns8";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Build tool and bindings loader for node-gyp that supports prebuilds";
      homepage = https://github.com/mafintosh/node-gyp-build;
      license = "MIT";
    };
    production = true;
  };
  webppl = nodeEnv.buildNodePackage {
    name = "webppl";
    packageName = "webppl";
    version = "0.9.11";
    src = fetchurl {
      url = "https://registry.npmjs.org/webppl/-/webppl-0.9.11.tgz";
      sha512 = "371qxqfaqwb6lvr11iwl9ij7qkx2ry6hrli58ilc19yrpmh5bsi37z9f2z8ca2vmrv4b6vrdyfp7dpjdw188n0caqxgqf99igci6hfc";
    };
    dependencies = [
      sources."adnn-2.0.10"
      sources."amdefine-1.0.1"
      sources."ast-types-0.9.14"
      sources."colors-1.1.2"
      (sources."escodegen-1.9.1" // {
        dependencies = [
          (sources."optionator-0.8.2" // {
            dependencies = [
              sources."prelude-ls-1.1.2"
              sources."deep-is-0.1.3"
              sources."wordwrap-1.0.0"
              sources."type-check-0.3.2"
              sources."levn-0.3.0"
              sources."fast-levenshtein-2.0.6"
            ];
          })
          sources."source-map-0.6.1"
        ];
      })
      (sources."esmangle-1.0.1" // {
        dependencies = [
          sources."esutils-1.0.0"
          (sources."esshorten-1.1.1" // {
            dependencies = [
              sources."estraverse-4.1.1"
              sources."esutils-2.0.2"
            ];
          })
          sources."estraverse-1.5.1"
          (sources."escope-1.0.3" // {
            dependencies = [
              sources."estraverse-2.0.0"
            ];
          })
          sources."source-map-0.1.43"
          sources."escodegen-1.3.3"
          (sources."optionator-0.3.0" // {
            dependencies = [
              sources."prelude-ls-1.1.2"
              sources."deep-is-0.1.3"
              sources."wordwrap-0.0.3"
              sources."type-check-0.3.2"
              sources."levn-0.2.5"
              sources."fast-levenshtein-1.0.7"
            ];
          })
          sources."esprima-1.1.1"
        ];
      })
      sources."esprima-3.1.3"
      (sources."estemplate-0.5.1" // {
        dependencies = [
          sources."esprima-2.7.3"
        ];
      })
      sources."estraverse-4.2.0"
      sources."esutils-2.0.2"
      sources."lodash-4.17.5"
      (sources."lru-cache-4.1.1" // {
        dependencies = [
          sources."pseudomap-1.0.2"
          sources."yallist-2.1.2"
        ];
      })
      sources."minimist-1.2.0"
      sources."present-1.0.0"
      sources."priorityqueuejs-1.0.0"
      sources."seedrandom-2.4.3"
      sources."source-map-0.5.7"
      sources."stack-trace-0.0.9"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Probabilistic programming for the web";
      homepage = http://webppl.org/;
      license = "MIT";
    };
    production = true;
  };
  npm = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "5.7.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-5.7.1.tgz";
      sha512 = "147xlh1d389j8yilssidlk7w8qgp1354y5p2bhv30a0m74vmfbl48859yfidij4ixbf0dhdmzkg6zz6viik2cskkrz4nw56zsz2nn5g";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = https://docs.npmjs.com/;
      license = "Artistic-2.0";
    };
    production = true;
  };
  canvas = nodeEnv.buildNodePackage {
    name = "canvas";
    packageName = "canvas";
    version = "1.6.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/canvas/-/canvas-1.6.9.tgz";
      sha1 = "e3f95cec7b16bf2d6f3fc725c02d940d3258f69b";
    };
    dependencies = [
      sources."nan-2.9.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Canvas graphics API backed by Cairo";
      homepage = https://github.com/Automattic/node-canvas;
      license = "MIT";
    };
    production = true;
  };
}